# Generated by Django 3.1.5 on 2021-02-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='temp',
            field=models.FloatField(default=False),
        ),
    ]
